---
# load-initial-data/tasks/main.yml
- name: load initial db data
  tags: load-initial-data
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}geoint/scale:{{ scale_docker_version }}'
    state: started
    tty: true
    command: 'load_all_data'
    env:
      SCALE_SECRET_KEY: '$6$D6zJhmUX3htFBnBk$Mkl/xVyXS2In5eHrwXz2QzzspaHPQPMFrfoA7DPxifGx.5O4kzedqx1DO5PrdSF0VuO1XqMEmpAhrXecPC5y51'
      SCALE_DEBUG: 'False'
      SCALE_DB_USER: '{{ db_username }}'
      SCALE_DB_PASS: '{{ db_password }}'
      SCALE_DB_HOST: '{{ db_host }}'
      MESOS_MASTER_URL: 'zk://scalemaster:2181/mesos'
      SCALE_DOCKER_IMAGE: '{{ docker_registry }}geoint/scale'
  become: true
