---
# vagrant.yml
# site file for vagrant cluster
# common requirements
- hosts: all
  roles:
    - common

# start a DNS server
- hosts: dns
  roles:
    - dns-server

# start and initialize the postgis server
- hosts: db
  roles:
    - postgis
    - db-init

# start an nfs server
- hosts: nfs
  roles:
    - nfs-server

# setup resolv.conf to point to the new DNS server
- hosts: all
  tags: resolvconf
  tasks:
    - name: Setup resolv.conf
      command: echo "nameserver 10.4.4.10" > /etc/resolv.conf
      become: true

# setup a docker registry
- hosts: registry
  roles:
    - docker-registry

# start mesos master and slaves
- include: mesos.yml

# start scale components
- include: scale.yml

# initialize example data
- hosts: build
  roles:
    - init-examples
